### ISSUE TITLE
E:1 create git instruction

### ISSUE THREAD

**Issue by JohnnyMahoney** [IT-Academy-Social-Projects-KRV/CMIYC#108]
cards not always closed when they are done, not all branches named as we talk, not all pull request have information like assignee, linked task, label,describe tasks in more detail, do not fix the errors of one feature in another, create a coherent instruction for such actions

**Comment by MrGold6** [comment]
Result: https://github.com/IT-Academy-Social-Projects-KRV/CMIYC/wiki/Git-instruction
