### ISSUE TITLE
Investigate how to setup database

### ISSUE THREAD

**Issue by MrGold6** [IT-Academy-Social-Projects-KRV/CMIYC#11]
E:3

How it works, can be explain this.
- "database first"
- "code first" 
- "schema first"

**Comment by Camper689** [comment]
### How to setup database:

1. Download MySQL 8.0.28 from https://dev.mysql.com/downloads/installer/
2. Install MySQL.
3. Create user with admin privileges.

### Database creation approach:
- **Code-first.** Scheme created and updated by generated scripts to match the entities in application.
- **Database-first.** In this approach, database and the related tables created first, then models are created from tables structure.
