### ISSUE TITLE
Research what technology we use

### ISSUE THREAD

**Issue by Ajderka** [IT-Academy-Social-Projects-KRV/CMIYC#12]
E:8

Decide on technology https://start.spring.io/
+ Testing

**Comment by Camper689** [comment]
## **Java 11**

### Java libraries:
- Spring web
- Spring authorization server
- Spring resource server

### Database:
- Spring boot JPA
- Flyway
- MySQL 8.0.28

### Tests:
- JUnit
- Mockito

### Utils:
- Lombok
- Postman

### IDE:
- Intellij IDEA
- VS Code
- Webstorm

### Other:
- Docker
- MSC generator
