### ISSUE TITLE
E:5 investigate different storigies (Google, AWS, Azure...). Pros and Cons?

### ISSUE THREAD

**Issue by ZX-pool** [IT-Academy-Social-Projects-KRV/CMIYC#61]

**Comment by PavelHorishny** [comment]
**Presentation of cloud services comparisons:**
https://docs.google.com/presentation/d/1nVDb21ZOHxkGSG9fka8BfC7lD8kbB7f2MMc2PkP119c/edit#slide=id.p
**Brief summary of cloud services' pros and cons:**
https://docs.google.com/spreadsheets/d/1cXjyPlBjyf31izMN7lAWOzeAWfYn8BvVa5RXt587hZI/edit#gid=0
